### ISSUE TITLE
Generic actor Tree implementation

### ISSUE THREAD

**Issue by alexytsu** [anorth/fvm-workbench#30]
The builtin actor's check_invariant's relies on loading a Tree which is a builtin-actors-specific type. 

The workbench cannot easily provide a Cid that is easily loaded as a `fil_builtin_actors_state::check::Tree`. In fact the current `VM::state_root` implementation in the workbench is incorrect as it has different semantics to the same method in the builtin-actor's test VM.

**Comment by alexytsu** [comment]
Instead of `VM::state_root` returning a Cid and constructing the ActorMap from within shared code, each implementation should create a generic ActorMap. 

- [ ] Lift the Map to the vm_api crate
- [ ] Implement an ActorMap representation in the fvm-workbench
- [ ] Refactor the builtin-actor's invariants check in terms of the ActorMap

**Comment by anorth** [comment]
The real FVM has a state tree impl which is also different to the builtin-actors, but is perhaps more canonical. An alternative might be to align all the sites on that one tree implementation, implemented in the built-in actors repo. Depending on point of view, I think one could say that the tree belonged there all along, or that it has no business being defined there. I'm not advocating for this, just pointing it out as an option.

@stebalien I'm interested in your thoughts here too.

**Comment by Stebalien** [comment]
In general, I think using a trait here makes sense (to help decouple tings). Although, if we're not careful, we'll end up with coherence issues.

---

In terms of moving the state tree into the builtin actors, that doesn't make sense (at the moment):

- The state-tree is manipulated entirely by the FVM.
- Moving it elsewhere will create circular dependencies (we already have those but, for the moment, they're limited to testing).

I'd like to eventually move the _entire_ state tree into the system actor, but that's a much larger refactor.

One possibility is to expose some basic state-tree types in `fvm_shared`. Specifically:

- `ActorState`
- `StateRoot` (already in shared, actually).

I'd also be open to introducing an entirely new `filecoin_state_tree` crate somewhere, either in the FVM repo or an entirely new repo.

---

Also note: most of the complexity in the state-tree logic in the FVM comes from gas accounting, caching, and reverts. None of those will be relevant outside the FVM itself. The only fields relevant outside of the FVM are:

https://github.com/filecoin-project/ref-fvm/blob/e9044cb8eca4ca928bede06689c4408b7837cc6f/fvm/src/state_tree.rs#L29-L32

**Comment by alexytsu** [comment]
Closed by https://github.com/filecoin-project/builtin-actors/pull/1459
