### ISSUE TITLE
Reward actor state summary check throws error

### ISSUE THREAD

**Issue by alexytsu** [anorth/fvm-workbench#31]
During state-invariant checking on the workbench VM, a (de)serialization error occurs when attempting to load the reward actor state. This occurs even if the reward actor state is checked immediately after genesis on a freshly instantiated VM. 

Some other actors (datatcap, multisig tested so far) are able to successfully have their state inspected with no issues. 

When attempting to load the RewardState from ActorState.state the following error is hit:
```
thread 'problematic_test' panicked at 'called `Result::unwrap()` on an `Err` value: Failed iterating map: Serialization error for Cbor protocol: RequireLength { name: "tuple", expect: 11, value: 6 }
```

**Comment by anorth** [comment]
Interesting. 11 is the right number of fields to expect. There could possibly be a bug in the reward actor state constructor (which never executes on mainnet), but it looks right to me. Or maybe it gets overwritten with something in genesis construction? Or later?

**Comment by alexytsu** [comment]
Copy-pasta bug in the way the manifest was being generated in workbench
